Hw8
smart48ru/Golang-Level1 pull request #10
Opened 2021-11-25 19:17 UTC by smart48ru

Kuznetsov Stas

2021-11-26 21:22 UTC, goarchitecture requested changes
Давайте всё-таки исправим:
Пусть у вас будет считывания с флагов ЛИБО енв.
yaml добавим к следующему ДЗ

2021-11-26 21:22 UTC, goarchitecture commented on .gitignore
> +go.sum
не нужен в гитигнор

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/configuration/main.go
> +var (
дефолтные значения либо делают константами, либо объявляют как переменные прямо внутри функции.
Здесь выводить это глобальным - не даёт никакой пользы

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/configuration/main.go
> +func ConfigurationFlag() Config {
функция имеет слово Flag в названии, но она читает и из флага и из yaml файлов

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/configuration/main.go
> +func ConfigurationFlag() Config {
функция может же и не считать конфиг. тогда что она должно вернуть?

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/configuration/main.go
> +				os.Exit(0)
не выходите - возвращайте ошибку.
Вы водите сообщение - то есть вы решаете за пользователя функций - что с этой ошибкой делать - что неявляется хорошим подхдом

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/configuration/main.go
> +			churl := checkUrl(Cfg.JaegerUrl)
то есть если мы считали из ямл то мы не валидируем?

2021-11-26 21:22 UTC, goarchitecture commented on LESSON8/main.go
> +	fmt.Printf("!! Program configuration !!\n%s\n\n", string(d))
подумайте, как можно использовать метод .String() для вывода конфига

2021-11-27 08:25 UTC, smart48ru commented on .gitignore
> +go.sum
исправил

2021-11-27 08:26 UTC, smart48ru commented on LESSON8/configuration/main.go
> +func ConfigurationFlag() Config {
Вы сказали переделать и убрать yaml. но учел и в след ДЗ реализую

2021-11-27 08:27 UTC, smart48ru commented on LESSON8/configuration/main.go
> +func ConfigurationFlag() Config {
Вы сказали переделать и убрать yaml. но учел и в след ДЗ реализую

2021-11-27 08:27 UTC, smart48ru commented on LESSON8/configuration/main.go
> +				os.Exit(0)
переписал данную функцию

2021-11-27 08:27 UTC, smart48ru commented on LESSON8/configuration/main.go
> +			churl := checkUrl(Cfg.JaegerUrl)
Вы сказали переделать и убрать yaml. но учел и в след ДЗ реализую

2021-11-27 08:28 UTC, smart48ru commented on LESSON8/main.go
> +	fmt.Printf("!! Program configuration !!\n%s\n\n", string(d))
Спасибо за подсказку в телеграмм.
Сделал.
Подскажите а какие еще есть встроеные методы или где о них почитать?

2021-12-02 09:16 UTC, merged