Hw3
smart48ru/Golang-Level1 pull request #3
Opened 2021-11-06 20:44 UTC by smart48ru

Home Work3
Кузнецов Стас

2021-11-06 22:58 UTC, goarchitecture commented
Хорошо. Доработайте по комментариям

2021-11-07 05:59 UTC, smart48ru commented
> Хорошо. Доработайте по комментариям

Не совсем ясно что именно надо доработать по комментариям. Если не сложно уточните что именно надо доработать.

2021-11-07 10:33 UTC, goarchitecture requested changes
код-ревью

2021-11-07 11:07 UTC, smart48ru reviewed
@goarchitecture Внес изменения по Вашим замечаниям

2021-11-07 13:18 UTC, smart48ru commented on LESSON3/main.go
> +			Calc()
HW1 и HW2 я уже смерджел в мэйн. Но ошибся и их файлы нечаянно подтянул в этот коммит.

2021-11-07 13:18 UTC, smart48ru commented on LESSON3/main.go
> +			var flag = 0
исправил

2021-11-07 13:19 UTC, smart48ru commented on LESSON3/main.go
> +			for i := 2; i <= m; i++ {
да Вы правы! Если делится на 2 то уже не простое.  Это сильно ускорило обработку...

2021-11-10 07:21 UTC, smart48ru commented on LESSON1/main.go
> +package main
я слил HW1 и HW2 в майн. НАверное этого не надо делать было....

2021-11-17 18:51 UTC, goarchitecture requested changes
Давайте ещё доработаем всё-таки для "Отлично".
Валидация - возвращайте ошибку.

Как завершите - стукните мне в телеграм в личку

2021-11-17 18:51 UTC, goarchitecture commented on LESSON3/main.go
> +	fmt.Scanln(&b)
и тут и далее на всех сканах

2021-11-17 18:51 UTC, goarchitecture commented on LESSON3/main.go
> +			Calc() //Тут я и хотел что бы при не верном вводе калькулятор перезапускался
вот чтобы не было рекурсии и нужно возвращать ошибки (комментарии об этом выше)

2021-11-17 18:51 UTC, goarchitecture commented on LESSON3/main.go
> +				for i := 2; i <= m; i++ {
тут мы проверяем деление на 2, 3, 4, 5, ....
Но если не делится на 2, то не делится ни на 4, ни на 6, ни на 8, ни на любые четные числа.
можно `i++` изменить на `i+=2`

Понятно, что можно так уйти совсем в дикую оптимизацию, просто это напрашивается так как просит всего лишь изменить `i++` на `i+=2` (и да, цикл тогда начнется с 3, а тогда на 2 нужно будет отдельно проверить - как у вас выше)

2021-11-20 14:22 UTC, merged